### ISSUE TITLE
Login to redfish server 172.17.0.1 failed with reason : null.

### ISSUE THREAD

**Issue by shadow7412** [Fish2/docker-storman#3]
I've recently switched to unraid, and am trying to install this so I can manage my old raid (with an intention to slowly migrate over to unraid's file management).

When firing this up, it seems to identify the raid card in the logs;

> Starting maxView Storage Manager WebServer Oct 22 14:34:07 Lime : [207] A controller has been added to the system: controller 1 ( Adaptec ASR78165 #3A271335334 Physical Slot: 17 ).

But when I go to the web interface, there are no controllers listed and instead I get this error in the event log.

> Login to redfish server 172.17.0.1 failed with reason : null.

Any ideas?

**Comment by Fish2** [comment]
@shadow7412 Not sure but might be worth trying it in host mode I have never worked with unraid so not sure on there network structure

**Comment by shadow7412** [comment]
![image](https://user-images.githubusercontent.com/286341/97794886-b0435c80-1c53-11eb-9b0d-8e598b63cb6d.png)
The network type is set to host, and it also has privileged turned on.

Just to be sure - are there any requirements that need to be installed on the host? It's the only thing that I can think of...

**Comment by Fish2** [comment]
No there's no requirement for the host side I may be that it need some work for unraid my host is Ubuntu I may look in to unraid in the future but you can fork and see if you can modify it and it it working

**Comment by JohnGalt1717** [comment]
I'm getting the same on Ubuntu 20.04

**Comment by Fish2** [comment]
> I'm getting the same on Ubuntu 20.04

what is your set command ?

**Comment by shadow7412** [comment]
6bb81fe48ec52badb4ab94771d7edc9f4df263df seems to have fixed it 👍
